apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-byf3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-byf3@sha256:ecca20232a748e47eb1825849086c89a59ed5322b8c4f9155ac72d11dd4dc18a
        name: my-python
        resources: {}
status: {}
